name: Generate Trophies

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: ryo-ma/github-profile-trophy@v2
        with:
          username: TiagoAntunes-Dev
          theme: flat
          margin-w: 0

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualiza os troféus do GitHub"
          file_pattern: 'trophy.svg'
